language: python
python:
    - "2.7"
    - "3.3"
    - "pypy"
env:
    - DJANGO=">=1.4.3,<1.5"
    - DJANGO=">=1.5,<1.6"
    - DJANGO=""
install:
    - "pip install -r ci_requirements.txt --use-mirrors"
    - "pip install django${DJANGO}"
before_script:
    - "pip install python-coveralls coverage"
script:
    - "coverage run runtests.py"
after_success:
    - "coveralls"
notifications:
    email: false
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=">=1.4.3,<1.5"
